### ISSUE TITLE
Failing with v1.11, every prior release worked.

### ISSUE THREAD

**Issue by vtog** [f5devcentral/f5-as3-config-converter#22]
### Environment
 * Application Services Version: v1.11.0
 * BIG-IP Version: v14.1.x

### Summary
Testing this with a simple config that worked with every version until v1.11.0.

### Steps To Reproduce
Using v1.11.0 I'm seeing the following error.
ubuntu@jumpbox:/Downloads/chacon$ sudo docker run --rm -v "$PWD":/app/data f5-as3-config-converter:v1.11.0 -o data/v14-test.json -u data/v14-test.ucs
1169 BIG-IP objects detected total
25 BIG-IP objects recognized by AS3
12 BIG-IP objects supported by ACC
5 AS3 stanzas generated
(node:1) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open 'data/v14-test.json'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at module.exports (/app/src/main.js:122:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ubuntu@jumpbox:/Downloads/chacon$ 

### Expected Behavior
Using every previous released vesion I get the expected json output.
ubuntu@jumpbox:/Downloads/chacon$ sudo docker run --rm -v "$PWD":/app/data f5-appsvcs-acc:1.10.0 -o data/v14-test.json -u data/v14-test.ucs
stdout: 1169 BIG-IP objects detected total
25 BIG-IP objects recognized by AS3
12 BIG-IP objects supported by Charon
4 AS3 stanzas generated

ubuntu@jumpbox:/Downloads/chacon$

**Comment by aheilmaier** [comment]
maybe a related to the one of @vtog
Also tried as REST-API service.
With version 1.10 lgt (f5-appsvcs-acc:1.10.0) 

`$ docker run --rm -v "$PWD":/app/data f5-as3-config-converter:v1.11.0 -o data/as3-out.json -u data/testucsfile.ucs
ERROR! DUPLICATE OBJECT NAME DETECTED:
abn-2020 exists as both Certificate and Certificate 

ERROR! DUPLICATE OBJECT NAME DETECTED:
VisaCallback exists as both Certificate and CA_Bundle 

ERROR! DUPLICATE OBJECT NAME DETECTED:
vali-2021 exists as both Certificate and Certificate 

ERROR! DUPLICATE OBJECT NAME DETECTED:
vali-2021 exists as both Certificate and Certificate 

ERROR! DUPLICATE OBJECT NAME DETECTED:
vali-2021 exists as both Certificate and Certificate 

ERROR! DUPLICATE OBJECT NAME DETECTED:
vali-2021 exists as both Certificate and Certificate 

ERROR! DUPLICATE OBJECT NAME DETECTED:
vali-2021 exists as both Certificate and Certificate 

ERROR! DUPLICATE OBJECT NAME DETECTED:
vali-2021 exists as both Certificate and Certificate 

ERROR! DUPLICATE OBJECT NAME DETECTED:
vali-2021 exists as both Certificate and Certificate 

ERROR! DUPLICATE OBJECT NAME DETECTED:
VisaCallback exists as both Certificate and CA_Bundle 

ERROR! DUPLICATE OBJECT NAME DETECTED:
valifc exists as both Certificate and CA_Bundle 

(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at findSchemaDefault (/app/src/removeDefaultValues.js:40:30)
    at /app/src/removeDefaultValues.js:62:33
    at Array.forEach (<anonymous>)
    at matchDefaults (/app/src/removeDefaultValues.js:60:10)
    at /app/src/removeDefaultValues.js:80:20
    at Array.forEach (<anonymous>)
    at findProfiles (/app/src/removeDefaultValues.js:76:10)
    at /app/src/removeDefaultValues.js:78:24
    at Array.forEach (<anonymous>)
    at findProfiles (/app/src/removeDefaultValues.js:76:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by mdditt2000** [comment]
will look at this issue tomorrow

**Comment by mdditt2000** [comment]
@v-zhuravlev-f5 is this the same issue as https://github.com/f5devcentral/f5-as3-config-converter/issues/23?

**Comment by sschadwick** [comment]
@mdditt2000 They look like the same issue, resolved in v1.12.0.

**Comment by vtog** [comment]
Just tested with v1.12.0, seeing same issue, and no output

❯ docker run --rm -v $PWD:/app/data/ f5-as3-config-converter:v1.12.0 -o data/clean-install.json -u data/clean-install.ucs
2021-05-25 21:05:24 INFO 175 BIG-IP objects detected total
2021-05-25 21:05:24 INFO 35 BIG-IP objects recognized by AS3
2021-05-25 21:05:24 INFO 22 BIG-IP objects supported by ACC
2021-05-25 21:05:24 INFO 9 AS3 stanzas generated
(node:1) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open 'data/clean-install.json'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at module.exports (/app/src/main.js:124:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mdditt2000** [comment]
@sschadwick @vtog is still seeing this issue on his ubuntu@jumpbox. I am going to create a issue in Jira

**Comment by mdditt2000** [comment]
created CHARON-306 for PM tracking. No milestone at this time

**Comment by sschadwick** [comment]
My mistake, #23 and the issue @aheilmaier mentioned should be addressed in v1.12.0.

**Comment by mdditt2000** [comment]
Setting milestone of 1.13 but cannot confirm until completed, however item is in the issue.

**Comment by mdditt2000** [comment]
Resolved in ACC 1.13

**Comment by vtog** [comment]
Confirmed fix in my test environment.... Thanks!
